export default function Head() {
  return (
    <>
      <title>MiscNinja - Supercharge Your AI Workflow</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/logo-supersmall.ico" />
    </>
  );
}
